"""Upgrade table users

Revision ID: 04dbb1d001cf
Revises: b26e282722ba
Create Date: 2023-09-18 12:24:36.106843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dbb1d001cf'
down_revision: Union[str, None] = 'b26e282722ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], )
    )
    op.drop_column('users', 'following_id')
    op.drop_column('users', 'followers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('followers')
    # ### end Alembic commands ###
