"""Upgrade table tweets

Revision ID: 815638ad9d36
Revises: a275fa008974
Create Date: 2023-09-18 20:51:20.841389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815638ad9d36'
down_revision: Union[str, None] = 'a275fa008974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('tweets_likes_id_fkey', 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'likes_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('likes_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tweets_likes_id_fkey', 'tweets', 'users', ['likes_id'], ['id'])
    op.drop_table('likes')
    # ### end Alembic commands ###
